windowrule {
    name = ClipboardManadger
    match:class = com.github.hluk.copyq
    float = on
    size = 400 500
    move = cursor_x cursor_y
    no_screen_share = on
}

windowrule {
    name = PictureInPicture
    match:title = Picture-in-Picture
    float = on
    size = 640 360
    move = monitor_w-window_w-20 monitor_h-window_h-20
    keep_aspect_ratio = on
}

windowrule {
    name = Discord Popout
    match:initial_title = Discord Popout
    float = on
    size = 640 384
    min_size = 0 0
    move = monitor_w-window_w-20 monitor_h-window_h-20
}

windowrule {
    name = Steam Notifications
    match:class = steam
    match:title = .*notificationtoasts.*
    rounding = 0
    monitor = 0
}

windowrule = float on, match:class xdg-desktop-portal-gtk

layerrule = blur on, blur_popups on, ignore_alpha 0, match:namespace quickshell
