windowrule = suppressevent maximize, class:.*
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0
windowrule = tile, class:^(Aseprite)$
windowrule = noinitialfocus, class:(jetbrains-)(.*), floating:1

layerrule = blur, eww
layerrule = ignorezero, eww
